name: Add card to programs triage board

on:
  issues:
     types: [closed, reopened, labeled]
 # issue_comment:
  
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:      
      - name: Add issue to Programs triage board
        if: "( contains(github.event.issue.labels.*.name, 'pg: request') ) || ( contains(github.event.issue.labels.*.name, 'G: Programs') )" 
        uses: lmkeston/github-actions-issue-to-work-item@v1.2-beta
        env:
           ado_token: "${{ secrets.ADO_PERSONAL_ACCESS_TOKEN }}"
           ado_organization: "lmkeston"
           ado_project: "Programs Triage"
           ado_area_path: "Programs Triage"
           ado_wit: "User Story"
           ado_new_state: "New"
           ado_close_state: "Closed"
           ado_bypassrules: true     
